name: Test Harness

on:
  issue_comment:
    types: [created]

jobs:
  test-harness:

    runs-on: ubuntu-latest

    steps:
    - uses: khan/pull-request-comment-trigger@master
      id: check
      with:
        trigger: '/test'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    - name: Get issue number  
      run: echo '{{ github.event.issue.number }}'
    - name: Actions API Test
      run: |
        echo "::log-command parameter1=qwe"
        echo "::set-env name=action_state::yellow"
        echo "::set-output name=action_fruit::strawberry"
        echo "::debug file=app.js,line=1::Entered octocatAddition method"
    - name: Print debug data
      run: |
        env
        docker info
        cat "$GITHUB_EVENT_PATH"
        ls -la "$GITHUB_WORKSPACE"
        echo "${{ github.head_ref}}"
    - name: Write some stuff, simulating test harness output
      run: |
        echo "My output" > "$GITHUB_WORKSPACE/output"
    - name: Take test harness output and respond to the comment with it
      run:
        cat "$GITHUB_WORKSPACE/output"
