name: Test Harness

on:
  issue_comment:
    types: [created]

jobs:
  test-harness:

    runs-on: ubuntu-latest

    steps:
    - uses: khan/pull-request-comment-trigger@master
      id: check
      with:
        trigger: '/test'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    # TODO: check for write access
    - name: 'Abort the execution'
      run: 'exit 1'
      if: steps.check.outputs.triggered != 'true'

    - name: Clone the PR branch
      uses: actions/checkout@v2
      with:
        lfs: true
        ref: 'refs/pull/${{ github.event.issue.number }}/head'
    - name: Gather info on the cloned code
      id: cloned
      run: echo "::set-output name=head_rev::$(git rev-parse HEAD)"
    # Doesn't work yet, see https://github.com/actions/cache/issues/176
    - name: Cache deb
      id: deb-cache
      uses: actions/cache@v1
      with:
        path: target/artifacts/vector-amd64.deb
        key: vector-test-harness-packaged-deb-${{ steps.cloned.outputs.head_rev }}
    #- name: Make deb
    #  if: steps.deb-cache.outputs.cache-hit != 'true'
    #  run: PASS_FEATURES=default-musl ./scripts/docker-run.sh builder-x86_64-unknown-linux-musl make build-archive package-deb

    - name: Invoke test harness
      uses: docker://timberiodev/vector-test-harness:latest
      with:
        args: |
          bash -c "cd /vector-test-harness \
          && bin/test -t docker_partial_events_merging_correctness -s vector \
          && bin/cohort -s vector | tee '${{ env.GITHUB_WORKSPACE }}/output'"
      env:
        GENERATE_SSH_KEY: true
        # VECTOR_TEST_CUSTOM_VECTOR_DEB_PATH: '${{ env.GITHUB_WORKSPACE }}/target/artifacts/vector-amd64.deb'
        VECTOR_TEST_USER_ID: 'gha_${{ github.event.issue.number }}'
        VECTOR_TEST_RESULTS_S3_BUCKET_NAME: test-results.vector.dev
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        ANSIBLE_EXTRA_ARGS: '-vvv'

    - name: Post a comment with the results
      uses: actions/github-script@0.4.0
      with:
        github-token: '${{secrets.GITHUB_TOKEN}}'
        script: |
          const fs = require('fs');
          const { promisify } = require('util');
          const readFileAsync = promisify(fs.readFile);

          const output = await readFileAsync(`${process.env.GITHUB_WORKSPACE}/output`);

          const body =
            'Test harness invocation complete!\n' +
            '\n' +
            '```\n' +
            output +
            '\n' +
            '```\n' +
            '\n' +
            `You can check the [execution log](${context.payload.repository.html_url}/actions/runs/${process.env.GITHUB_RUN_ID}) to learn more!`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          })
      if: always()
