name: Test Harness

on:
  issue_comment:
    types: [created]

jobs:
  test-harness:

    runs-on: ubuntu-latest

    steps:
    - uses: khan/pull-request-comment-trigger@master
      id: check
      with:
        trigger: '/test'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    - name: Print debug data
      run: |
        set -x
        env
        docker info
        cat "$GITHUB_EVENT_PATH"
        ls -la "$GITHUB_WORKSPACE"
        echo "{{ github.head_ref}}"
    - name: Write some stuff, simulating test harness output
      run: |
        echo "My output" > "$GITHUB_WORKSPACE/output"
    - name: Take test harness output and respond to the comment with it
      run:
        set +x
        cat "$GITHUB_WORKSPACE/output"
