name: Test Harness

on:
  issue_comment:
    types: [created]

jobs:
  test-harness:

    runs-on: ubuntu-latest

    steps:
    - uses: khan/pull-request-comment-trigger@master
      id: check
      with:
        trigger: '/test'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    - name: Print debug data
      run: |
        env
        docker info
      
