name: Test Harness

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print debug data
      run: |
        env
        docker info
      
